//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public int Label_ID { get; set; }
        public string LabelKey { get; set; }
        public string LabelName { get; set; }
        public int Language_ID { get; set; }
        public int Page_ID { get; set; }
    }
}
